Repository Benjent/nice-resume, pull requests merged in 2024-03, with the labels that each got.

#2 fix: typescript issues
  src/components/Editor.vue
  src/stores/resume.ts
  src/types/index.ts
Labels: bug

#3 feat: allow up and down move of work experience and education
  src/components/Editor.vue
  src/components/ListActions.vue
  src/utils/array.ts
Labels: enhancement

#1 ci: Add Node.js Action
  .github/workflows/test.yaml
  .node-version
  .nvmrc
  .vscode/settings.json
  package-lock.json
  package.json
Labels: enhancement, help wanted, good first issue

#23 fix(Benjent2023.vue): make background take whole color available
  src/components/templates/Benjent2023.vue
Labels: bug

#24 Feat/use utils for task crud
  src/components/Editor.vue
Labels: enhancement
